;;; package --- My size modes

(defun joe-enbiggen ()
  (interactive)
  (set-face-attribute 'default nil :height 150)
  )
(defun joe-enbiggish ()
  (interactive)
  (set-face-attribute 'default nil :height 130)
  )
(defun joe-ennormal ()
  (interactive)
  (set-face-attribute 'default nil :height 120)
  )
(defun joe-enmassive ()
  (interactive)
  (set-face-attribute 'default nil :height 160)
  )
(defun joe-enhugen ()
  (interactive)
  (set-face-attribute 'default nil :height 200)
  )

(when (eq system-type 'gnu/linux)
  (joe-ennormal))
